@startuml CarAggregationUML

class CarAggregation {
    - engine: EngineAggregation
    + CarAggregation(EngineAggregation)
    + drive(): void
    + {static} main(String[]): void
}

class EngineAggregation {
    + start(): void
}

CarAggregation "1" o-- "1" EngineAggregation : Has (Aggregation)

@enduml