@startuml CarDependencyUML

class CarDependency {
    +drive(engine: EngineDependency)
    +park(engine: EngineDependency)
}

class EngineDependency {
    +start()
    +stop()
}

CarDependency "1" ..> "1" EngineDependency : Uses (Dependency)

@enduml